### ISSUE TITLE
THIS IS LITERALLY WHAT I DID 16 DAYS AGO ON GITHUB

### ISSUE THREAD

**Issue by atalhaoui** [TupleDev/KeyAuthHook#1]
Pasted code. Pasted from me

**Comment by TupleDev** [comment]
wow the ego that you have

**Comment by TupleDev** [comment]
you are talking about that, i gave you credits + that method is already patched by keyauth, while mine isn't.

**Comment by TupleDev** [comment]
omfg yes i did steal your idea but your code dont work

**Comment by TupleDev** [comment]
discord injector? you clearly didn't look at the source code
HydraHook i gave him all credits that he deserves
KDtour ? didn't see 1 detour library for kernel

while you have forked repos and nothing that is yours else then that "keyauth-hook" that is retarded, very bad coded, and using a pasters library "MinHook"

**Comment by TupleDev** [comment]
you cant make your own library lol

**Comment by TupleDev** [comment]
cry cry baby
